######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "C:/RCProjectDir/trunk/RCproject/RCproject.srcs/sources_1/edk/project_core"
if { [xload new project_core.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

xset binfo 

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl vhdl
save proj
exit
